const phrases = {
    variety: [
        "Endless possibilities",
        "Embrace the unknown",
        "Explore new horizons",
        "Infinite diversity",
        "Unlimited potential",
        "Dare to dream",
        "Open your mind",
        "Expand your horizons",
        "Think outside the box",
        "Dream big",
        "Break free",
        "Create your destiny",
        "Embrace change",
        "Discover yourself",
        "Be adventurous",
        "Find your passion",
        "Take a chance",
        "Live your truth",
        "Seek new adventures",
        "Challenge yourself",
        "Discover the magic",
        "Never give up",
        "Follow your heart",
        "Find your purpose",
        "Believe in yourself",
        "Unlock your potential",
        "Seize the day",
        "Embrace the journey",
        "Trust your instincts",
        "Chart your own course",
        "Find your inner strength",
        "Explore the possibilities",
        "Reach for the stars",
        "Embrace the moment",
        "Live with purpose",
        "Push your limits",
        "Dream, explore, discover",
        "Create your own path",
        "Embrace your uniqueness",
        "Step out of your comfort zone",
        "Live life to the fullest",
        "Chase your dreams",
        "Find beauty in simplicity",
        "Be fearless",
        "Be the change",
        "Carve your own path",
        "Dream, believe, achieve",
        "Follow your dreams",
        "Trust the journey",
        "Live your best life",
        "Explore, dream, discover",
        "Find joy in the journey",
        "Leap of faith",
        "Create your own destiny",
        "Live in the moment",
        "Seek adventure",
        "Believe in the impossible",
        "Discover the unknown",
        "Break the mold",
        "Challenge the status quo",
        "Find your inner voice",
        "Embrace the possibilities",
        "Find your inner peace",
        "Live with intention",
        "Embrace the chaos",
        "Trust your journey",
        "Explore the world",
        "Find your inner fire",
        "Embrace your journey",
        "Unlock your creativity",
        "Embrace your inner child",
        "Find your balance",
        "Embrace the challenge",
        "Discover new possibilities",
        "Step into the unknown",
        "Be true to yourself",
        "Find your happiness",
        "Live passionately",
        "Dream, believe, succeed",
        "Embrace the adventure",
        "Create your own adventure",
        "Follow your passion",
        "Dream, explore, live",
        "Trust your path",
        "Live without regrets",
        "Embrace your dreams",
        "Find your inspiration",
        "Embrace the magic",
        "Trust your journey",
        "Create your own magic",
        "Find your spark",
        "Embrace the journey",
        "Live with purpose",
        "Trust your instincts",
        "Explore the possibilities",
        "Follow your heart",
        "Dream big",
        "Find your passion",
        "Seek new adventures",
        "Believe in yourself",
        "Unlock your potential",
        "Embrace the moment",
        "Live life to the fullest",
        "Chase your dreams",
        "Find beauty in simplicity",
        "Carve your own path",
        "Live your best life",
        "Explore, dream, discover",
        "Believe in the impossible",
        "Challenge the status quo",
        "Embrace the possibilities",
        "Find your inner peace",
        "Embrace the chaos",
        "Explore the world",
        "Embrace your journey",
        "Unlock your creativity",
        "Find your balance",
        "Discover new possibilities",
        "Be true to yourself",
        "Find your happiness",
        "Live passionately",
        "Embrace the adventure",
        "Follow your passion",
        "Trust your path",
        "Embrace your dreams",
        "Embrace the magic",
        "Find your spark",
        "Explore the possibilities",
        "Follow your heart",
        "Find your passion",
        "Believe in yourself",
        "Embrace the moment",
        "Chase your dreams",
        "Live your best life",
        "Explore the world",
        "Find your happiness",
        "Follow your passion",
        "Trust the journey",
        "Dream big",
        "Create your own path",
        "Discover the magic",
        "Break the mold",
        "Trust your journey",
        "Explore the world",
        "Embrace your journey",
        "Live with intention",
        "Embrace the challenge",
        "Dream, believe, succeed",
        "Create your own adventure",
        "Find your inspiration",
        "Embrace the magic",
        "Create your own magic",
        "Find your spark",
        "Trust your journey",
        "Dream big",
        "Find your passion",
        "Unlock your potential",
        "Live life to the fullest",
        "Believe in the impossible",
        "Embrace the possibilities",
        "Trust your instincts",
        "Follow your heart",
        "Find your happiness",
        "Live passionately",
        "Believe in yourself"            
    ],
    funAndGames: [
        "Game on!",
        "Let the games begin",
        "Join the fun",
        "It's playtime!",
        "Fun for everyone",
        "Laugh out loud",
        "Get ready to party",
        "Let's have a blast",
        "Play to win",
        "Hit the jackpot",
        "Roll the dice",
        "Time to celebrate",
        "Ready, set, go!",
        "Be a team player",
        "Enjoy the ride",
        "Live for the moment",
        "Feel the adrenaline",
        "Ready for action",
        "Challenge accepted",
        "Party like a rockstar",
        "Dance the night away",
        "Score big",
        "Play it cool",
        "Winning isn't everything",
        "Keep calm and play on",
        "Get your game face on",
        "Game night",
        "Let loose and have fun",
        "Bring your A-game",
        "It's all fun and games",
        "Go big or go home",
        "Time to shine",
        "The thrill of victory",
        "Play by the rules",
        "Life is a game",
        "Game changer",
        "Ready for anything",
        "Play with passion",
        "Game over",
        "Hit the target",
        "Unleash your inner child",
        "Get in the game",
        "Born to play",
        "Fun and games",
        "Winner takes all",
        "Live it up",
        "Play like there's no tomorrow",
        "No pain, no gain",
        "Game on, world off",
        "Fun times ahead",
        "Make it a game changer",
        "Turn up the fun",
        "The joy of play",
        "Let's get wild",
        "Play it safe",
        "Time to party",
        "Fun and excitement",
        "Play it your way",
        "Winning is the goal",
        "Fun for all ages",
        "Live life to the fullest",
        "Play for keeps",
        "Life is a game, play it",
        "Stay focused and play",
        "Let's get this party started",
        "Play hard, play fair",
        "Game face on",
        "Time to shine",
        "Game night",
        "The fun never stops",
        "Life's a game, play it",
        "Winning is everything",
        "Keep calm and play",
        "Game on, party on",
        "It's all about fun",
        "The thrill of the game",
        "Game time",
        "Ready to play",
        "Let the good times roll",
        "Game day",
        "Fun in the sun",
        "Playtime is anytime",
        "Ready for some fun",
        "Play with heart",
        "Enjoy the journey",
        "Play it loud",
        "Play it cool",
        "Playtime is the best time",
        "The power of play",
        "Game on, have fun",
        "Playtime is fun time",
        "Game on, have a blast",
        "Game on, party time",
        "Play on, game on",
        "Fun and excitement",
        "Play for fun",
        "Play to win",
        "It's all about the game",
        "Game on, play hard",
        "Get ready to play",
        "Fun and games",
        "The game of life",
        "Let the games begin",
        "Play to have fun",
        "Fun times ahead",
        "Play with confidence",
        "Game on, let's play",
        "Play to win, have fun",
        "Keep calm and play on",
        "It's game time",
        "Game on, play on",
        "Game on, let's have fun",
        "Let's play a game",
        "The joy of playing",
        "Game on, play fair",
        "Game on, game over",
        "Life is a game, play it well",
        "Game on, play to win",
        "Game on, play it safe",
        "Play to win, play fair",
        "Play for keeps, have fun",
        "Game on, play with passion",
        "Game on, play like a champion",
        "Game on, play with heart",
        "Game on, play like there's no tomorrow",
        "Game on, play hard",
        "Game on, play it cool",
        "Game on, play it loud",
        "Game on, play like a pro",
        "Game on, play it smart",
        "Game on, play it your way",
        "Game on, play it big",
        "Game on, play it bold",
        "Game on, play with style",
        "Game on, play it fast",
        "Game on, play it slow",
        "Game on, play it smooth",
        "Game on, play it rough",
        "Game on, play it wild",
        "Game on, play it strong",
        "Game on, play it fierce",
        "Game on, play it fearless",
        "Game on, play it fun",
        "Game on, play it crazy",
        "Game on, play it awesome",
        "Game on, play it fantastic",
        "Game on, play it incredible",
        "Game on, play it legendary",
        "Game on, play it epic",
        "Game on, play it outstanding",
        "Game on, play it phenomenal",
        "Game on, play it extraordinary",
        "Game on, play it unbelievable",
        "Game on, play it unbeatable"
    ],
    entertainment: [
        "May the Force be with you",
        "To infinity and beyond",
        "Elementary, my dear Watson",
        "Hasta la vista, baby",
        "I'll be back",
        "Bond, James Bond",
        "You can't handle the truth",
        "Say hello to my little friend",
        "I see dead people",
        "Keep calm and carry on",
        "Winter is coming",
        "I am Iron Man",
        "With great power comes great responsibility",
        "You're a wizard, Harry",
        "Do or do not, there is no try",
        "Just keep swimming",
        "Here's Johnny!",
        "I'm king of the world!",
        "I'm Batman",
        "Live long and prosper",
        "You shall not pass!",
        "Houston, we have a problem",
        "I'll never let go, Jack",
        "There's no place like home",
        "I volunteer as tribute",
        "May the odds be ever in your favor",
        "Luke, I am your father",
        "I'm walking here!",
        "Go ahead, make my day",
        "I'm the king of the world",
        "The force will be with you, always",
        "I'm not bad. I'm just drawn that way",
        "I am your father",
        "I feel the need – the need for speed",
        "Here's looking at you, kid",
        "I'm gonna make him an offer he can't refuse",
        "A dream is a wish your heart makes",
        "I'm flying, Jack",
        "There's no crying in baseball",
        "As you wish",
        "What we've got here is failure to communicate",
        "I see you",
        "To infinity and beyond!",
        "I'll have what she's having",
        "Here's Johnny",
        "Mama always said life was like a box of chocolates",
        "I'll be back!",
        "Why so serious?",
        "You talking to me?",
        "Toto, I've got a feeling we're not in Kansas anymore",
        "E.T. phone home",
        "I see dead people",
        "Here's looking at you, kid",
        "There's no place like home",
        "I'll make him an offer he can't refuse",
        "Hasta la vista, baby",
        "May the Force be with you",
        "You can't handle the truth!",
        "You had me at 'hello'",
        "Here's Johnny!",
        "Here's Johnny",
        "You had me at hello",
        "You can't handle the truth",
        "I feel the need – the need for speed!",
        "You're gonna need a bigger boat",
        "There's no crying in baseball!",
        "I'm the king of the world",
        "Say hello to my little friend!",
        "I'm the king of the world!",
        "I see dead people",
        "I'll be back",
        "You're gonna need a bigger boat!",
        "You talking to me?",
        "To infinity and beyond",
        "You had me at hello",
        "Why so serious?",
        "You had me at hello.",
        "Why so serious?",
        "To infinity and beyond!",
        "You talking to me?",
        "There's no crying in baseball",
        "May the Force be with you.",
        "I see dead people.",
        "I'm the king of the world!",
        "You can't handle the truth",
        "I'll be back.",
        "You're gonna need a bigger boat.",
        "There's no crying in baseball!",
        "You're gonna need a bigger boat!",
        "Why so serious?",
        "I'm the king of the world",
        "Here's Johnny!",
        "I see dead people",
        "You're gonna need a bigger boat!",
        "May the Force be with you",
        "Here's looking at you, kid",
        "You can't handle the truth!",
        "Why so serious?",
        "You talking to me?",
        "I'll be back",
        "I'm the king of the world!",
        "May the Force be with you.",
        "You had me at hello",
        "Say hello to my little friend!",
        "You're gonna need a bigger boat",
        "I see dead people",
        "You can't handle the truth",
        "To infinity and beyond",
        "Why so serious?",
        "Here's looking at you, kid",
        "You talking to me?",
        "May the Force be with you",
        "Say hello to my little friend",
        "You're gonna need a bigger boat",
        "Why so serious?",
        "You had me at hello",
        "I see dead people",
        "You can't handle the truth",
        "To infinity and beyond",
        "May the Force be with you",
        "Here's looking at you, kid",
        "Why so serious?",
        "You talking to me?",
        "You had me at hello",
        "I see dead people",
        "You're gonna need a bigger boat",
        "May the Force be with you",
        "I'm the king of the world!",
        "Say hello to my little friend!"
    ],
    everydayLife: [
        "Morning coffee",
        "Running errands",
        "Walking the dog",
        "Cooking dinner",
        "Reading a book",
        "Taking a nap",
        "Doing laundry",
        "Cleaning the house",
        "Grocery shopping",
        "Listening to music",
        "Watching TV",
        "Checking email",
        "Sending texts",
        "Making breakfast",
        "Packing lunch",
        "Going to work",
        "Coming home",
        "Exercising daily",
        "Playing sports",
        "Taking a shower",
        "Brushing teeth",
        "Having a snack",
        "Having lunch",
        "Having dinner",
        "Watering plants",
        "Folding clothes",
        "Ironing clothes",
        "Reading the news",
        "Playing video games",
        "Taking a walk",
        "Driving a car",
        "Cycling outdoors",
        "Paying bills",
        "Meeting friends",
        "Going to the gym",
        "Attending meetings",
        "Cooking dinner",
        "Playing with pets",
        "Doing homework",
        "Working from home",
        "Shopping online",
        "Writing in a journal",
        "Making phone calls",
        "Taking photos",
        "Listening to podcasts",
        "Walking in the park",
        "Doing yoga",
        "Meditating daily",
        "Going for a run",
        "Relaxing at home",
        "Playing board games",
        "Making crafts",
        "Going for a hike",
        "Taking public transit",
        "Planning vacations",
        "Attending parties",
        "Celebrating birthdays",
        "Having family dinners",
        "Decluttering space",
        "Organizing closet",
        "Watching sunsets",
        "Watching sunrises",
        "Attending concerts",
        "Going to the movies",
        "Visiting museums",
        "Taking day trips",
        "Attending weddings",
        "Shopping at malls",
        "Walking in nature",
        "Going to the beach",
        "Having a picnic",
        "Playing in the snow",
        "Building snowmen",
        "Decorating for holidays",
        "Preparing for exams",
        "Baking cookies",
        "Trying new recipes",
        "Going on road trips",
        "Playing with kids",
        "Gardening outdoors",
        "Planting flowers",
        "Having barbecues",
        "Attending festivals",
        "Learning new skills",
        "Reading bedtime stories",
        "Having movie nights",
        "Enjoying outdoor activities",
        "Playing musical instruments",
        "Going to farmers markets",
        "Doing home improvement projects",
        "Volunteering in the community",
        "Hosting dinner parties",
        "Enjoying staycations",
        "Creating scrapbooks",
        "Going fishing",
        "Going camping",
        "Exploring new neighborhoods",
        "Going to amusement parks",
        "Playing with Legos",
        "Building puzzles",
        "Having spa days",
        "Going horseback riding",
        "Having sleepovers",
        "Attending sports events",
        "Trying new restaurants",
        "Going to the zoo",
        "Going to the aquarium",
        "Visiting historical sites",
        "Going to flea markets",
        "Having family game nights",
        "Writing letters",
        "Going stargazing",
        "Having bonfires",
        "Catching fireflies",
        "Building sandcastles",
        "Having slumber parties",
        "Having potluck dinners",
        "Going to art galleries",
        "Having karaoke nights",
        "Having talent shows",
        "Going roller skating",
        "Going ice skating",
        "Playing frisbee",
        "Having spa nights",
        "Playing mini golf",
        "Playing laser tag",
        "Going bowling",
        "Going to escape rooms",
        "Having science experiments",
        "Attending book clubs",
        "Doing crossword puzzles",
        "Doing Sudoku puzzles",
        "Building model kits",
        "Having tea parties",
        "Having fashion shows",
        "Having puppet shows",
        "Having magic shows",
        "Doing role-playing games",
        "Going birdwatching",
        "Going fishing",
        "Going crabbing",
        "Going hiking",
        "Having picnics",
        "Going skiing",
        "Going snowboarding",
        "Having snowball fights",
        "Having snow days",
        "Going sledding",
        "Going tubing",
        "Building snow forts",
        "Going to concerts",
        "Going to music festivals",
        "Going to flea markets",
        "Going to farmers markets",
        "Going to art fairs",
        "Going to craft fairs",
        "Going to car shows",
        "Going to air shows",
        "Going to boat shows",
        "Going to parades",
        "Going to carnivals",
        "Going to fairs",
        "Going to theme parks",
        "Going to water parks",
        "Going to trampoline parks"
    ],
    world: [
        "Renaissance era",
        "Industrial Revolution",
        "Ancient civilizations",
        "Age of Exploration",
        "World Wars",
        "Space exploration",
        "Globalization effects",
        "Cultural exchange",
        "Technological advancements",
        "Human migration",
        "Colonization history",
        "Cultural diversity",
        "Industrialization impact",
        "Revolutionary movements",
        "Great Depression",
        "Cold War era",
        "Post-war reconstruction",
        "World heritage sites",
        "Scientific discoveries",
        "Natural wonders",
        "Historical landmarks",
        "Environmental conservation",
        "Modern art movements",
        "Political revolutions",
        "Famous landmarks",
        "Archeological discoveries",
        "Medieval history",
        "Historical figures",
        "Social justice movements",
        "Economic globalization",
        "Cultural revolutions",
        "Colonial legacies",
        "Civil rights movements",
        "Renaissance art",
        "Urbanization trends",
        "Humanitarian efforts",
        "Human rights struggles",
        "Maritime exploration",
        "Renewable energy",
        "Historical artifacts",
        "Space race",
        "Artificial intelligence",
        "Fossil fuel dependency",
        "Global conflicts",
        "Cultural traditions",
        "Political ideologies",
        "Climate change impact",
        "Economic development",
        "World religions",
        "Artistic expressions",
        "Historical documents",
        "Ancient wonders",
        "Social media influence",
        "Global pandemics",
        "Technological revolutions",
        "Historical revolutions",
        "Cultural assimilation",
        "Industrial innovations",
        "Global trade routes",
        "Political upheavals",
        "Environmental degradation",
        "Natural disasters",
        "Historical conquests",
        "Exploration voyages",
        "Global communication",
        "Cultural exchange programs",
        "Arts and literature",
        "Colonial expansion",
        "Social movements",
        "Historical breakthroughs",
        "Technological breakthroughs",
        "Cultural preservation",
        "Natural conservation",
        "Historical landmarks",
        "Ancient civilizations",
        "Modern cultural phenomena",
        "Global economy",
        "World conflicts",
        "Historical migrations",
        "Space exploration",
        "Industrialization",
        "Cultural heritage",
        "Global citizenship",
        "Worldwide epidemics",
        "Environmental awareness",
        "Historical monuments",
        "International diplomacy",
        "Global challenges",
        "Cultural revolutions",
        "Colonial legacies",
        "Arts and culture",
        "Historical periods",
        "World languages",
        "Humanitarian efforts",
        "Global cooperation",
        "Historical landmarks",
        "Political ideologies",
        "Climate change impacts",
        "Economic globalization",
        "World religions",
        "Artistic expressions",
        "Historical documents",
        "Ancient wonders",
        "Social media influence",
        "Global pandemics",
        "Technological revolutions",
        "Historical revolutions",
        "Cultural assimilation",
        "Industrial innovations",
        "Global trade routes",
        "Political upheavals",
        "Environmental degradation",
        "Natural disasters",
        "Historical conquests",
        "Exploration voyages",
        "Global communication",
        "Cultural exchange programs",
        "Arts and literature",
        "Colonial expansion",
        "Social movements",
        "Historical breakthroughs",
        "Technological breakthroughs",
        "Cultural preservation",
        "Natural conservation",
        "Historical landmarks",
        "Ancient civilizations",
        "Modern cultural phenomena",
        "Global economy",
        "World conflicts",
        "Historical migrations",
        "Space exploration",
        "Industrialization",
        "Cultural heritage",
        "Global citizenship",
        "Worldwide epidemics",
        "Environmental awareness",
        "Historical monuments",
        "International diplomacy",
        "Global challenges",
        "Cultural revolutions",
        "Colonial legacies",
        "Arts and culture",
        "Historical periods",
        "World languages",
        "Humanitarian efforts",
        "Global cooperation",
        "Historical landmarks",
        "Political ideologies",
        "Climate change impacts",
        "Economic globalization",
        "World religions",
        "Artistic expressions",
        "Historical documents",
        "Ancient wonders",
        "Social media influence",
        "Global pandemics",
        "Technological revolutions",
        "Historical revolutions",
        "Cultural assimilation",
        "Industrial innovations",
        "Global trade routes",
        "Political upheavals",
        "Environmental degradation",
        "Natural disasters",
        "Historical conquests",
        "Exploration voyages",
        "Global communication",
        "Cultural exchange programs",
        "Arts and literature",
        "Colonial expansion"
    ]
}